# Generated by Django 4.1.7 on 2023-02-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0002_service_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='imagefiles/')),
                ('qualification', models.CharField(max_length=225)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app10.service_tb')),
            ],
        ),
    ]
