# Generated by Django 4.1.7 on 2023-03-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0004_contact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact1_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phonenumber', models.CharField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
    ]
