# Generated by Django 4.1.7 on 2023-03-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0005_contact1_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phonenumber', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('depid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app10.service_tb')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app10.doctor_tb')),
            ],
        ),
    ]
