# Generated by Django 4.1.7 on 2023-03-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0007_alter_appoinment_tb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment_tb',
            name='depid',
        ),
    ]
