# Generated by Django 4.1.7 on 2023-03-10 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0008_remove_appoinment_tb_depid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_tb',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imagefiles/'),
            preserve_default=False,
        ),
    ]
